name: CI

on:
  push:
    branches:
      - '**'
  repository_dispatch:
    types: [update]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: cache deps
        uses: actions/cache@main
        with:
          path: |
            node_modules
            */*/*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install deps
        run: yarn

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test

  deploy:
    needs: build
    if: ${{ github.event_name != 'pull_request' && contains(github.ref, 'main') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: cache deps
        uses: actions/cache@main
        with:
          path: |
            node_modules
            */*/*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Snap
        run: yarn snap

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'khaos-functions'
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
